"""rename department

Revision ID: 07a68061afb0
Revises: acf4fcf57297
Create Date: 2024-10-08 11:52:04.955685

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "07a68061afb0"
down_revision = "acf4fcf57297"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
