"""rename address

Revision ID: 828a3e945d04
Revises: 07a68061afb0
Create Date: 2024-10-08 11:57:37.656550

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "828a3e945d04"
down_revision = "07a68061afb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
